In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)


[1 2 3 4 5]


In [3]:
arr2 = np.arange(10)  # Creates an array with values from 0 to 9
print(arr2)


[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr_zeros = np.zeros((3, 4))  # Creates a 3x4 array of zeros
arr_ones = np.ones((2, 3))    # Creates a 2x3 array of ones
print(arr_zeros)
print(arr_ones)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print(arr_zeros.size)  # Prints (5,), meaning it's a 1-dimensional array with 5 elements
print(arr_zeros)	
print(arr2.dtype)  # Prints int64, indicating¬¬¬¬¬¬¬ the array contains 64-bit integers


12
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
int64


In [12]:
arr3 = np.array([1, 2, 3, 4, 5,6])
arr4 = np.array([10, 20, 30, 40, 50])

# Element-wise addition
result_add = arr3 + arr4
print(result_add)

# Element-wise multiplication
result_mul = arr3 * arr4
print(result_mul)


ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [15]:
arr5 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Slicing rows and columns
print(arr5[0])    # Prints the first row: [1 2 3]
print(arr5[:, 1]) # Prints the second column: [2 5 8]



[1 2 3]
[2 5]


In [16]:

arr6 = np.array([1, 2, 3, 4, 5])

# Square root
print(np.sqrt(arr6))
# [1.         1.41421356 1.73205081 2.         2.23606798]

# Exponential
print(np.exp(arr6)) 
# [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
