In [ ]:
### Load in NumPy (remember to pip install numpy first)

In [7]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``o

In [2]:
import numpy as np

In [ ]:
### The Basics

In [24]:
a = np.array([1,2,3], dtype='int64')
print(a)
print(a.dtype) 

[1 2 3]
int64


In [10]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [16]:
# Get Dimension
b.ndim

2

In [15]:
# Get Shape
a.shape

(3,)

In [17]:
# Get Type
a.dtype

dtype('int32')

In [26]:
# Get Size
a.itemsize


8

In [27]:
# Get total size
a.nbytes


24

In [28]:
# Get number of elements
a.size

3

In [ ]:
### Accessing/Changing specific elements, rows, columns, etc

In [33]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
a.ndim

2

In [38]:
# Get a specific element [r, c]
a[0,0]

np.int64(1)

In [39]:
# Get a specific row 
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [42]:
# Get a specific column
a[:, 2]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [55]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, -1:-6:-2]

array([7, 5, 3])

In [22]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [59]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# Get specific element (work outside in)
b[0,1,1]

np.int64(4)

In [26]:
# replace 
b[:,1,:] = [[9,9,9],[8,8]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [28]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
### Initializing Different Types of Arrays

In [29]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [62]:
# Any other number
np.full((2,3), 999)

array([[999, 999, 999],
       [999, 999, 999]])

In [63]:
# Any other number (full_like)
np.full_like(b, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [33]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.99857996, 0.61879909],
       [0.8893832 , 0.69287106],
       [0.73061549, 0.44619776],
       [0.58653874, 0.62438308]])

In [66]:
# Random Integer values
np.random.randint(0,100, size=(4,3))

array([[15, 52, 41],
       [23, 22, 87],
       [15, 90, 83],
       [76, 57, 59]], dtype=int32)

In [67]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [73]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
##### Be careful when copying arrays!!!

In [79]:
a = np.array([1,2,3])
b = a.copy()
#b = a
b[0] = 100
print(a)

[1 2 3]


In [ ]:
### Mathematics

In [40]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [41]:
a + 2

array([3, 4, 5, 6])

In [42]:
a - 2

array([-1,  0,  1,  2])

In [43]:
a * 2

array([2, 4, 6, 8])

In [44]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [45]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [46]:
a ** 2

array([ 1,  4,  9, 16])

In [47]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

In [ ]:
##### Linear Algebra

In [49]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [50]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

In [ ]:
##### Statistics

In [51]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.min(stats)

np.int64(1)

In [53]:
np.max(stats, axis=1)

array([3, 6])

In [54]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [ ]:
### Reorganizing Arrays

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [61]:
import numpy as np

before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

# Reshape into (2, 3)
after = before.reshape((2, 2, 2))  # Corrected to match the total number of elements
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [ ]:
### Miscellaneous
##### Load Data from File

In [58]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [ ]:
##### Boolean Masking and Advanced Indexing

In [59]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])