<a href="https://colab.research.google.com/github/vasanthidharmalingam/day2updation/blob/main/python_fdp_(day_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
my_str="vasanthi"
print(my_str[7])
print("A" in my_str)

i
False


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [ ]:
arr1=np.arange(1)
print(arr1)

[0]


In [ ]:
arr1=np.zeros((3,3))
arr2=np.ones((2,3))
print(arr1)
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
arr0=np.array([[1,2],[2,3]],dtype='int32')
arr1=np.array([1,2,3,4,5])
arr2=np.array([100,200,300,400,500])
arr3=arr1+arr2
print(arr3)
arr4=arr1*arr2
print(arr4)
arr5=arr1/arr2
print(arr5)
print(arr0.shape)
print(arr2.size)
print(arr0.dtype)
print(np.sqrt(arr1))

[101 202 303 404 505]
[ 100  400  900 1600 2500]
[0.01 0.01 0.01 0.01 0.01]
(2, 2)
5
int32
[1.         1.41421356 1.73205081 2.         2.23606798]


In [ ]:
help(np.sqrt)

Help on ufunc:

sqrt = <ufunc 'sqrt'>
    sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Return the non-negative square-root of an array, element-wise.
    
    Parameters
    ----------
    x : array_like
        The values whose square-roots are required.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is 

In [ ]:
import numpy as np
arr1=np.array([1,2,3,4,5],[1,2,3,4,5])
print(arr1[0,0])

TypeError: Field elements must be 2- or 3-tuples, got '1'

In [ ]:
a = np.array([1,2,3], dtype='int64')
print(a)
print(a.dtype)

[1 2 3]
int64


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b.ndim

2

In [ ]:
a.shape

(3,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.itemsize

8

In [ ]:
b.nbytes

72

In [ ]:
b[2,2]

9

In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype='int64')
print(b)
b.itemsize

[[1 2 3]
 [4 5 6]
 [7 8 9]]


8

In [ ]:
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [ ]:
a = np.array([1,2,3], dtype='int64')
np.full_like(a, 99)

array([99, 99, 99])

In [ ]:
np.random.rand(2,4)

array([[0.57634196, 0.03995698, 0.666967  , 0.68328999],
       [0.39803732, 0.88857641, 0.91996905, 0.4851974 ]])

In [ ]:
np.random.randint(0,4, size=(2,3))

array([[2, 0, 3],
       [1, 1, 0]])

In [ ]:
output=np.zeros((7,7))
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
x=np.ones((3,3))
x[2,2]=7
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 7.]]


In [ ]:
output[2:-2,2:-2]=x
print(output)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
a=np.array([1,2,3])
b=a.copy()
b[0]=10
print(a)

[1 2 3]
